Add estate sheet with compatibility phone and tablet, and color to estate list.
Tgarfr/Project-9-RealEstateManager pull request #4
Opened 2023-06-22 08:22 UTC by Tgarfr

Add estate sheet with compatibility phone and tablet, and color to estate list.

2023-06-25 17:06 UTC, FGuyet requested changes

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/api/FakeEstateApi.kt
> +            Estate(1,"Estate 1",Estate.Type.HOUSE,250000.00,100F,3, 2, 5,"Anchored bay a vast marble gallery with sweeping staircase, the entertaining floor includes a baronial living room facing Par
Pour la lisibilité, je te conseille de rajouter les noms d'arguments devant chaque argument et de faire une ligne par argument pour la compréhension (facile avec cmd sur l'un des arguments, ça te le proposera pour les deux)

pour avoir quelque chose qui ressemble à 
```kotlin
Estate(
    id = 1,
    name = "Estate 1",
    type  = Estate.Type.HOUSE, 
    ...
)
```

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/api/FakeEstateApi.kt
> +            Estate(3,"Estate 3",Estate.Type.DUPLEX,1000000.00,100F,3, 2, 5,"Anchored bay a vast marble gallery with sweeping staircase, the entertaining floor includes a baronial living room facing P
Extraire la longue string de description dans une constante de classe, pour la lisibilité. En Kotlin, la notion de static est représenté par un companion object (object partagé avec toutes les instances de cette classe) :

```kotlin
companion object {
    private val FAKE_DESCRIPTION =  "Anchored bay a vast marble gallery with sweeping staircase, the entertaining floor includes a baronial living room facing Park Avenue, handsome library with original paneling, and tremendous dining room; all of which enjoy fireplaces. The state-of-the-art St. Charles designed kitchen includes a sunny breakfast room and staff quarters. Upstairs, the expansive master suite overlooks Park Avenue and includes two marble baths, two dressing rooms, and two offices. Additionally the are three large bedrooms with en-suite bath and media."
}
```

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateListAdapter.kt
> +        if (lastSelectedEstate == estate) {
```suggestion
        else {
```

Si ça te permet de ne pas garder "lastSelectedEstate" en mémoire

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateListAdapter.kt
> +        }
```suggestion
        val lastSelected = this.selectedEstate
        this.selectedEstate = selectedEstate
        if (lastSelectedEstate != null) {
            notifyItemChanged(currentList.indexOf(lastSelectedEstate))
        }
        if (selectedEstate != null) {
            notifyItemChanged(currentList.indexOf(selectedEstate))
        }
```

Si tu veux éviter de garder last en mémoire

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateListAdapter.kt
> +    fun updateSelectedEstateColor(selectedEstate: Estate?) {
Suggestion : renommer en `fun selectEstate(estate : Estate?)` ?

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateListFragmentViewModel.kt
> +    fun setSelectedEstateLiveData(estate: Estate) {
renommer en `fun selectEstate(estate:Estate)`, c'est étrange d'avoir la notion de liveData ici

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateSheetFragment.kt
> +            surfaceTextView.text = estate?.surface.toString()
```suggestion
            descriptionTextView.text = estate?.description ?: ""
            surfaceTextView.text = estate?.surface?.toString() ?: ""
```

Mettre "" par défaut éviterait d'afficher "null" à l'écran si l'un des estate a un de ces champs à null

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateSheetFragment.kt
> +            surfaceTextView.text = estate?.surface.toString()
appliquer une visibility du TextView à `Gone` peut être préférable selon le cas.

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateSheetFragmentViewModel.kt
> +        estateListObserver = Observer { estateList ->
Tu peux l'initier au même endroit que la définition de la variable en Kotlin, pas besoin de le faire dans le constructeur

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateSheetFragmentViewModel.kt
> +        estateListObserver = Observer { estateList ->
Ca permet de définir estateListObserver en val au lieu de var au passage

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateSheetFragmentViewModel.kt
> +            if (estateRepository.getSelectedEstateLiveData().value == null && estateList != null && estateList.isNotEmpty()) {
isNullOrEmpty()
```suggestion
            if (estateRepository.getSelectedEstateLiveData().value == null && !estateList.isNullOrEmpty()) {
```

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateSheetFragmentViewModel.kt
> +    }
C'est un bon candidat pour introduire les fonctions et propriétés d'extension en Kotlin, et "l'élevation du return" : 

```suggestion
    val Estate.locationString : String get() = if (estate.additionalAddress == null) {
        "{$estate.houseNumber} ${estate.street}\n${estate.city}\n${estate.zipCode}\n${estate.country}"
    } else {
        "${estate.houseNumber} ${estate.street}\n${estate.additionalAddress}\n${estate.city}\n${estate.zipCode}\n${estate.country}"
    }
```

Ca te permet d'accéder en appelant simplement : 

```kotlin
val estate : Estate? = ...
val location = estate?.locationString ?: ""
```

2023-06-25 17:06 UTC, FGuyet commented on app/src/main/res/values-land/config.xml
> +    <bool name="isLandscapeMode">true</bool>
Je pense qu'il est préférable de récupérer l'info de la configuration directement au lieu de passer par un boolean dans les ressources. Ca dupplique l'info ^^

https://stackoverflow.com/questions/2795833/check-orientation-on-android-phone

2023-06-25 18:20 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/api/FakeEstateApi.kt
> +            Estate(1,"Estate 1",Estate.Type.HOUSE,250000.00,100F,3, 2, 5,"Anchored bay a vast marble gallery with sweeping staircase, the entertaining floor includes a baronial living room facing Par
Ok

2023-06-25 18:20 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/api/FakeEstateApi.kt
> +            Estate(3,"Estate 3",Estate.Type.DUPLEX,1000000.00,100F,3, 2, 5,"Anchored bay a vast marble gallery with sweeping staircase, the entertaining floor includes a baronial living room facing P
Ok merci

2023-06-26 10:58 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/api/FakeEstateApi.kt
> +            Estate(3,"Estate 3",Estate.Type.DUPLEX,1000000.00,100F,3, 2, 5,"Anchored bay a vast marble gallery with sweeping staircase, the entertaining floor includes a baronial living room facing P
Je ne peut pas faire de companion objet dans un objet, mais je vais le mettre dans une constante

2023-06-26 11:00 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateListAdapter.kt
> +        }
Je l'utilise aussi dans le onBindViewHolder

2023-06-26 11:01 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateListAdapter.kt
> +        if (lastSelectedEstate == estate) {
Mais du coup on rechange la couleur de tous les élements de la liste, cela fait plus de calcul que de garder une valeur en mémoire.

2023-06-26 11:02 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateListAdapter.kt
> +    fun updateSelectedEstateColor(selectedEstate: Estate?) {
Oui tu a raison :)

2023-06-26 11:04 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateSheetFragment.kt
> +            surfaceTextView.text = estate?.surface.toString()
Je vais empêcher les nuls sur ses champs à la création.

2023-06-26 11:22 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateSheetFragmentViewModel.kt
> +        estateListObserver = Observer { estateList ->
Ok :)

2023-06-26 11:46 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateSheetFragmentViewModel.kt
> +            if (estateRepository.getSelectedEstateLiveData().value == null && estateList != null && estateList.isNotEmpty()) {
Ok :)

2023-06-26 11:52 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateSheetFragmentViewModel.kt
> +    }
Comment tu lui passe le paramétre estate ?

2023-06-26 11:57 UTC, Tgarfr commented on app/src/main/res/values-land/config.xml
> +    <bool name="isLandscapeMode">true</bool>
Ok :)

2023-06-26 12:01 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateSheetFragmentViewModel.kt
> +    }
Je valide la PR pour avancer, mais on parlera de se point mercredi et je modifirai après.

2023-06-26 12:03 UTC, merged

2023-06-26 12:41 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateSheetFragmentViewModel.kt
> +    }
OK :) en attendant tu peux aussi consulter la doc Kotlin : https://kotlinlang.org/docs/extensions.html#extension-properties