Add estate add
Tgarfr/Project-9-RealEstateManager pull request #5
Opened 2023-06-27 08:08 UTC by Tgarfr

Add estate add

2023-06-27 18:41 UTC, FGuyet requested changes

2023-06-27 18:41 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/repository/EstateRepository.kt
> +        }
```suggestion
        val estateList: List<Estate> = estateListLiveData.value ?: return
        
            val mutableEstateList: MutableList<Estate> = estateList.toMutableList()
            mutableEstateList.add(estate)
            estateListLiveData.value = mutableEstateList.toList()
           
```

2023-06-27 18:41 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateAddFragment.kt
> +                        type = type!!,
Ne jamais utiliser `!!` en Kotlin, il y a toujours un moyen de mieux gérer le cas.

Par exemple, mettre une valeur par defaut ou ne pas permettre de valider le formulaire si le type n'est pas renseigné

2023-06-27 18:41 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateAddFragment.kt
> +                        type = type!!,
Je vois que tu as géré le cas où le type n'est pas renseigné. Vu que c'est une var, le compilateur ne t'assure pas qu'il sera toujours non null une fois que cette ligne de code sera exécutée.

Une solution sera de mettre d'utiliser une val locale à la fonction que tu utilisera pour le null-check et la création de l'objet estate.

2023-06-27 18:41 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateAddFragment.kt
> +                    viewModel.addEstate(estate)
```suggestion
                    viewModel.addEstate(estate)
                    Toast.makeText(activity, resources.getString(R.string.add_estate_added), Toast.LENGTH_LONG).show()
```
Toujours mieux de feedback une fois l'action réellement faite ;)

2023-06-27 18:41 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateAddFragment.kt
> +                    viewModel.addEstate(estate)
Dans un projet plus complet, tu seras surement amené à gérer les échecs (avec un Result en retour de fonction par exemple), ça te permet de de l'afficher qu'en cas de succès : 

```kotlin
viewModel.addEstate(estate)
    .onSuccess {
        Toast.makeText(activity, resources.getString(R.string.add_estate_added), Toast.LENGTH_LONG).show()
    }.onFailture { 
        Toast.makeText(activity, resources.getString(R.string.add_estate_addition_failed), Toast.LENGTH_LONG).show()
    }
```

--> Mais je ne pense pas qu'il soit nécessaire de le faire dans le cadre de ce projet.

2023-06-27 18:41 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateTypeSpinnerAdapter.kt
> +        view = convertView ?: LayoutInflater.from(parent?.context).inflate(R.layout.item_type_estate_list, parent, false)
```suggestion
        val view: View = convertView ?: LayoutInflater.from(parent?.context)
                .inflate(R.layout.item_type_estate_list, parent, false)
```

2023-06-28 07:49 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateAddFragment.kt
> +                        type = type!!,
Mais cette valeur est modifié dans :
`private val onSelectedType = object : AdapterView.OnItemSelectedListener`
donc on est obligé d'utiliser un var

2023-06-28 07:50 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateAddFragment.kt
> +                    viewModel.addEstate(estate)
Ok

2023-06-28 12:48 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/repository/EstateRepository.kt
> +        }
Ok super

2023-06-28 12:50 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateAddFragment.kt
> +                        type = type!!,
Ok j'ai mis une variable local

2023-06-28 12:50 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/EstateAddFragment.kt
> +                    viewModel.addEstate(estate)
Tu me montera ça en vision sa m'interesse

2023-06-28 12:58 UTC, merged