Add loan simulator
Tgarfr/Project-9-RealEstateManager pull request #9
Opened 2023-07-12 05:59 UTC by Tgarfr

Add loan simulator

2023-07-13 18:20 UTC, FGuyet requested changes

2023-07-13 18:20 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/LoanSimulatorActivity.kt
> +                viewModel.calculateTotalCoast(years, amount, rate, bring).toString()
```suggestion
                viewModel.calculateTotalCost(years, amount, rate, bring).toString()
```

2023-07-13 18:20 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/LoanSimulatorActivityViewModel.kt
> +    private var totalPayment: MutableLiveData<Double> = MutableLiveData(0.0)
```suggestion
    private val monthlyPaymentLiveData: MutableLiveData<Double> = MutableLiveData(0.0)
    private val totalInterestsLiveData: MutableLiveData<Double> = MutableLiveData(0.0)
    private val totalPayment: MutableLiveData<Double> = MutableLiveData(0.0)
```

2023-07-13 18:20 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/LoanSimulatorActivityViewModel.kt
> +    fun getTotalPaymentLiveData() = totalPayment
En Kotlin, je retrouve souvent les variables mutables privées en avec le suffix `_` et les valeurs publiques non mutables définit de la sorte (

```suggestion
    private val _monthlyPaymentLiveData: MutableLiveData<Double> = MutableLiveData(0.0)
    val monthlyPaymentLiveData 
        get() = _monthlyPaymentLiveData as LiveData<Double>
    
    // or
    
    private val _totalInterestsLiveData: MutableLiveData<Double> = MutableLiveData(0.0)
    val _totalInterestsLiveData: LiveData<Double> 
        get() = _totalInterestsLiveData
    ```

2023-07-13 18:21 UTC, FGuyet commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/LoanSimulatorActivityViewModel.kt
> +    fun getTotalPaymentLiveData() = totalPayment
un exemple : https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?hl=fr#3

2023-07-14 06:07 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/LoanSimulatorActivity.kt
> +                viewModel.calculateTotalCoast(years, amount, rate, bring).toString()
LOL :)

2023-07-14 06:08 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/LoanSimulatorActivityViewModel.kt
> +    private var totalPayment: MutableLiveData<Double> = MutableLiveData(0.0)
:)

2023-07-14 06:15 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/LoanSimulatorActivityViewModel.kt
> +    fun getTotalPaymentLiveData() = totalPayment
Ok très interessant merci

2023-07-14 06:17 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/LoanSimulatorActivityViewModel.kt
> +    fun getTotalPaymentLiveData() = totalPayment
Je vais resté sur mon écriture actuel car cela correspond aux cours Openclassrooms, et j'ai peut de tomber sur un évaluateur qui ne connaît pas.

2023-07-14 06:56 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/LoanSimulatorActivity.kt
> +                viewModel.calculateTotalCoast(years, amount, rate, bring).toString()
https://github.com/Tgarfr/Project-9-RealEstateManager/pull/9/commits/b63ae5962956a79244292f97b6587b51d02d9a6e

2023-07-14 06:56 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/LoanSimulatorActivityViewModel.kt
> +    private var totalPayment: MutableLiveData<Double> = MutableLiveData(0.0)
https://github.com/Tgarfr/Project-9-RealEstateManager/pull/9/commits/b63ae5962956a79244292f97b6587b51d02d9a6e

2023-07-14 06:56 UTC, Tgarfr commented on app/src/main/java/com/openclassrooms/realestatemanager/ui/LoanSimulatorActivityViewModel.kt
> +    fun getTotalPaymentLiveData() = totalPayment
https://github.com/Tgarfr/Project-9-RealEstateManager/pull/9/commits/b63ae5962956a79244292f97b6587b51d02d9a6e

2023-07-14 07:46 UTC, FGuyet approved these changes

2023-07-14 09:15 UTC, merged